# Test Numpy array


Array can have many dimensions


In [1]:
# test array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
print(arr.ndim)  # num dimension

(2, 4)
2


Array can be reshaped to any shape

- A shape is a view of original array


In [ ]:
# reshape
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr.base)

# copy
print("copy")
copyArr = newarr.copy()
print(copyArr)
print(copyArr.base)
print(copyArr.reshape(-1))  # flatten array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
copy
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
None
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Use `nditer()` to iterate through the elements of the multi dimension array


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


Use `ndenumerate()` to iterate over both the array's indices and values. Indices are in a tuple type.


In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Concat and Stack array


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)  # concat along dimension 0
print("----axis 0\n", arr)

arr = np.concatenate((arr1, arr2), axis=1)  # concat along dimension 1
print("----axis 1\n", arr)

----axis 0
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
----axis 1
 [[1 2 5 6]
 [3 4 7 8]]


Stacking is same as concatenation, the only difference is that stacking is done along a new axis


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# we can't concat 2 arrays with axis=1 (out of dimension)
# arr = np.concatenate((arr1, arr2), axis=1) # ERROR!

arr = np.stack((arr1, arr2), axis=0)
print(arr)
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [36]:
# arr1 = np.array([[[1, 2], [3, 4]]])
# arr2 = np.array([[[6, 7], [8, 9]]])

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# [
# arr1,
# arr2,
# ]
arr = np.vstack((arr1, arr2))
print(arr)

# [ ...arr1, ...arr2 ]
arr = np.hstack((arr1, arr2))  # like concat 2 arrays
print(arr)

# depth stack make 3D array (it will shape the input arrays to an 3D array)
arr = np.dstack((arr1, arr2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


Split array


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
print(type(newarr))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
<class 'list'>


### Filter array

it need a boolean array which will be used to filter the array. if index is true then it will be included in the filtered array.


In [39]:
# basic
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

filtering = [True, False, True, False, True]

arr2 = arr1[filtering]

print(arr2)

[1 3 5]


In [ ]:
# filter directly
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
filtering = arr1 > 3

print(filtering)
print(arr1[filtering])

[False False False  True  True]
[4 5]


Random from array numbers with probability

In [3]:
from numpy import random
from collections import Counter

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

# Count occurrences using Counter
counter = Counter(x)
for number, count in counter.items():
    print(f"Number {number} occurs {count} times")

[7 7 7 7 5 7 7 7 5 3 5 5 5 5 5 7 7 5 3 3 7 7 7 7 5 5 5 7 5 7 7 7 7 3 3 5 7
 7 3 7 7 7 7 3 7 7 7 7 5 5 5 7 3 7 5 7 5 5 5 7 3 5 7 7 5 7 7 5 7 7 7 7 5 7
 5 5 7 7 7 7 5 7 5 7 7 5 5 5 7 7 7 7 7 7 3 5 7 7 5 3]
Number 7 occurs 56 times
Number 5 occurs 33 times
Number 3 occurs 11 times
